### ISSUE TITLE
Python needed?

### ISSUE THREAD

**Issue by Fr34k9** [atagulalan/arctis-battery-percentage#18]
> gyp ERR! find Python You need to install the latest version of Python.
> gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
> gyp ERR! find Python you can try one of the following options:

Is it possible that python is needed? Or what am i doing wrong?

**Comment by atagulalan** [comment]
Could you try to install windows-build-tools with `npm install --global --production windows-build-tools`

Thank you.

**Comment by Fr34k9** [comment]
Did this. 
`C:\Users\Fr34k\AppData\Roaming\npm\arctis-battery -> C:\Users\Fr34k\AppData\Roaming\npm\node_modules\arctis-battery-percentage\percentage.js
+ arctis-battery-percentage@1.0.4
updated 1 package in 2.403s`

Following error appears now:
`Error: Could not locate the bindings file. Tried:
 → C:\Users\Fr34k\AppData\Roaming\npm\node_modules\arctis-battery-percentage\node_modules\node-hid\build\HID.node
 → C:\Users\Fr34k\AppData\Roaming\npm\node_modules\arctis-battery-percentage\node_modules\node-hid\build\Debug\HID.node
 → C:\Users\Fr34k\AppData\Roaming\npm\node_modules\arctis-battery-percentage\node_modules\node-hid\build\Release\HID.node
 → C:\Users\Fr34k\AppData\Roaming\npm\node_modules\arctis-battery-percentage\node_modules\node-hid\out\Debug\HID.node
 → C:\Users\Fr34k\AppData\Roaming\npm\node_modules\arctis-battery-percentage\node_modules\node-hid\Debug\HID.node
 → C:\Users\Fr34k\AppData\Roaming\npm\node_modules\arctis-battery-percentage\node_modules\node-hid\out\Release\HID.node
 → C:\Users\Fr34k\AppData\Roaming\npm\node_modules\arctis-battery-percentage\node_modules\node-hid\Release\HID.node
 → C:\Users\Fr34k\AppData\Roaming\npm\node_modules\arctis-battery-percentage\node_modules\node-hid\build\default\HID.node
 → C:\Users\Fr34k\AppData\Roaming\npm\node_modules\arctis-battery-percentage\node_modules\node-hid\compiled\14.15.1\win32\x64\HID.node
 → C:\Users\Fr34k\AppData\Roaming\npm\node_modules\arctis-battery-percentage\node_modules\node-hid\addon-build\release\install-root\HID.node
 → C:\Users\Fr34k\AppData\Roaming\npm\node_modules\arctis-battery-percentage\node_modules\node-hid\addon-build\debug\install-root\HID.node
 → C:\Users\Fr34k\AppData\Roaming\npm\node_modules\arctis-battery-percentage\node_modules\node-hid\addon-build\default\install-root\HID.node
 → C:\Users\Fr34k\AppData\Roaming\npm\node_modules\arctis-battery-percentage\node_modules\node-hid\lib\binding\node-v83-win32-x64\HID.node
    at bindings (C:\Users\Fr34k\AppData\Roaming\npm\node_modules\[4marctis-battery-percentage[24m\node_modules\[4mbindings[24m\bindings.js:126:9)
    at loadBinding (C:\Users\Fr34k\AppData\Roaming\npm\node_modules\[4marctis-battery-percentage[24m\node_modules\[4mnode-hid[24m\nodehid.js:25:42)
    at Object.showdevices [as devices] (C:\Users\Fr34k\AppData\Roaming\npm\node_modules\[4marctis-battery-percentage[24m\node_modules\[4mnode-hid[24m\nodehid.js:127:5)
    at Object.<anonymous> (C:\Users\Fr34k\AppData\Roaming\npm\node_modules\[4marctis-battery-percentage[24m\percentage.js:7:19)
[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:928:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  tries: [
    [32m'C:\\Users\\Fr34k\\AppData\\Roaming\\npm\\node_modules\\arctis-battery-percentage\\node_modules\\node-hid\\build\\HID.node'[39m,
    [32m'C:\\Users\\Fr34k\\AppData\\Roaming\\npm\\node_modules\\arctis-battery-percentage\\node_modules\\node-hid\\build\\Debug\\HID.node'[39m,
    [32m'C:\\Users\\Fr34k\\AppData\\Roaming\\npm\\node_modules\\arctis-battery-percentage\\node_modules\\node-hid\\build\\Release\\HID.node'[39m,
    [32m'C:\\Users\\Fr34k\\AppData\\Roaming\\npm\\node_modules\\arctis-battery-percentage\\node_modules\\node-hid\\out\\Debug\\HID.node'[39m,
    [32m'C:\\Users\\Fr34k\\AppData\\Roaming\\npm\\node_modules\\arctis-battery-percentage\\node_modules\\node-hid\\Debug\\HID.node'[39m,
    [32m'C:\\Users\\Fr34k\\AppData\\Roaming\\npm\\node_modules\\arctis-battery-percentage\\node_modules\\node-hid\\out\\Release\\HID.node'[39m,
    [32m'C:\\Users\\Fr34k\\AppData\\Roaming\\npm\\node_modules\\arctis-battery-percentage\\node_modules\\node-hid\\Release\\HID.node'[39m,
    [32m'C:\\Users\\Fr34k\\AppData\\Roaming\\npm\\node_modules\\arctis-battery-percentage\\node_modules\\node-hid\\build\\default\\HID.node'[39m,
    [32m'C:\\Users\\Fr34k\\AppData\\Roaming\\npm\\node_modules\\arctis-battery-percentage\\node_modules\\node-hid\\compiled\\14.15.1\\win32\\x64\\HID.node'[39m,
    [32m'C:\\Users\\Fr34k\\AppData\\Roaming\\npm\\node_modules\\arctis-battery-percentage\\node_modules\\node-hid\\addon-build\\release\\install-root\\HID.node'[39m,
    [32m'C:\\Users\\Fr34k\\AppData\\Roaming\\npm\\node_modules\\arctis-battery-percentage\\node_modules\\node-hid\\addon-build\\debug\\install-root\\HID.node'[39m,
    [32m'C:\\Users\\Fr34k\\AppData\\Roaming\\npm\\node_modules\\arctis-battery-percentage\\node_modules\\node-hid\\addon-build\\default\\install-root\\HID.node'[39m,
    [32m'C:\\Users\\Fr34k\\AppData\\Roaming\\npm\\node_modules\\arctis-battery-percentage\\node_modules\\node-hid\\lib\\binding\\node-v83-win32-x64\\HID.node'[39m
  ]
}`
Any idea?

**Comment by atagulalan** [comment]
Could you try to delete node_modules folder and run `npm install` again?

**Comment by Fr34k9** [comment]
Yes. But this didn't change anything in the behaviour. Everyhing looks fine. As soon as I exec "arctis-battery" the binding error appears.
https://i.imgur.com/CNS3Ivm.png

**Comment by tobichenx3** [comment]
I receive the same thing.
