### ISSUE TITLE
issues with installing 

### ISSUE THREAD

**Issue by njcxqqy** [atagulalan/arctis-battery-percentage#19]
im new to nodejs

i keep on getting this line in my code

`prebuild-install WARN install No prebuilt binaries found (target=14.15.4 runtime=node arch=x64 libc= platform=win32)`

then followed by this 

`warning c4290 c++ exception specification ignored`
 
is there anyway to fix ?
could it be the reason that i have do not have the system in English ?

thank you.

**Comment by atagulalan** [comment]
Try to match node version 10 or 12.

Make sure you have Microsoft Visual C++ Redistributables installed. You can install it here: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

I did not test any foreign languages, including my mother tongue, Turkish. But I highly doubt that language is the reason.

Thank you.

**Comment by njcxqqy** [comment]
i have now try on v12 and v10 

This is what im getting on v12

`C:\Users\\arctis-battery-percentage-master>npm install --only=prod

> node-hid@1.2.0 install C:\Users\\arctis-battery-percentage-master\node_modules\node-hid
> prebuild-install || node-gyp rebuild

npm WARN arctis-battery-percentage@1.0.4 No repository field.

added 64 packages from 46 contributors and audited 95 packages in 2.418s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities


C:\Users\\arctis-battery-percentage-master>node createImages
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- C:\Users\\arctis-battery-percentage-master\createImages.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:667:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:887:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at Object.<anonymous> (C:\Users\\arctis-battery-percentage-master\createImages.js:1:26)
[90m    at Module._compile (internal/modules/cjs/loader.js:999:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:863:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:708:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\\\arctis-battery-percentage-master\\createImages.js'[39m
  ]
}`


i dont want to push to the next step with warnings yet 

thank you.

**Comment by atagulalan** [comment]
The output is perfectly normal. `npm install` works.

Which headset model do you have?

It looks like program could not find it. You can check if it's seeing headset by running `node list`. If it halts, comment out these lines in `list.js`:

```
      device.write([0x06, 0x18])
      var report = device.readSync()
      console.log(deviceInfo, report)
```

And add `console.log(deviceInfo)` above that.

File should look like this:

```
#!/usr/bin/env node

const path = require('path')
var HID = require('node-hid')
HID.setDriverType('libusb')

var devices = HID.devices()

// Caution: This sends data to EVERY HID device connected.
// If you know the vendorId and productId of your device,
// please uncomment filter section.

devices
  //.filter(d => d.vendorId === VENDORID && d.productId === PRODUCTID && d.usage !== 1)
  .forEach((deviceInfo) => {
    try {
      var device = new HID.HID(deviceInfo.path)
      console.log(deviceInfo)
      //device.write([0x06, 0x18])
      //var report = device.readSync()
      //console.log(deviceInfo, report)
      device.close()
    } catch (error) {
      console.log('Not a steelseries wireless device.')
    }
  })
```

You can check SteelSeries devices connected to your PC. 
Please share the output here.

Thank you.

**Comment by njcxqqy** [comment]
arctis 9
`{
  vendorId: 4152,
  productId: 4802,
  path: '\\\\?\\hid#vid_1038&pid_12c2&mi_02#8&2be896cf&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
  manufacturer: 'SteelSeries',
  product: 'SteelSeries Arctis 9',
  release: 113,
  interface: 2,
  usagePage: 65280,
  usage: 1
}
{
  vendorId: 4152,
  productId: 4802,
  path: '\\\\?\\hid#vid_1038&pid_12c2&mi_00#8&1533599f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
  manufacturer: 'SteelSeries',
  product: 'SteelSeries Arctis 9',
  release: 113,
  interface: 0,
  usagePage: 65472,
  usage: 1
}`
`{
  vendorId: 4152,
  productId: 4804,
  path: '\\\\?\\hid#vid_1038&pid_12c4&mi_05#8&75224b7&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
  serialNumber: '000000000000',
  manufacturer: 'SteelSeries',
  product: 'SteelSeries Arctis 9',
  release: 3,
  interface: 5,
  usagePage: 12,
  usage: 1
}
{
  vendorId: 4152,
  productId: 4802,
  path: '\\\\?\\hid#vid_1038&pid_12c2&mi_01#8&390a9761&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
  manufacturer: 'SteelSeries',
  product: 'SteelSeries Arctis 9',
  release: 113,
  interface: 1,
  usagePage: 12,
  usage: 1
}`

thank you.
