### ISSUE TITLE
NPM Install issue

### ISSUE THREAD

**Issue by kenomote** [atagulalan/arctis-battery-percentage#28]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/atagulalan/arctis-battery-percentage.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2021-10-22T11_07_24_403Z-debug.log

**Comment by kenomote** [comment]
How do I fix this?

**Comment by kenomote** [comment]
Im new to npm and installing from git, I already fixed the above issue by simply installing git. However the final command throws me this error:



C:\Users\lenovo>node percentage
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\lenovo\percentage'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

**Comment by atagulalan** [comment]
Hey @kenomote 

You are in wrong folder. First, navigate to project folder by `cd [path]`. Example: `cd C:\Users\lenovo\Desktop\arctis-battery-percentage`

You can run `npm install` there. This would install necessary packages.

After this, please try to run `node percentage`

Thank you.

**Comment by LazoYoung** [comment]
Confirm you have Git installed on your windows?
